cargo: "Change and Configuration Analyst"
empresa: "Kruger Inc."
fecha: "2025-10-25"
modalidad: "híbrido"
descripcion: |
 
  This position reports to the IT Service Manager. 
 

requerimientos:
 
  - Solid understanding of ITIL processes, especially Change and Configuration Management.
  - Experience managing data quality in a CMDB or similar system.
  - Proficiency in interpreting reports and metrics to drive decisions.
  - Strong facilitation skills (e.g., running CABs or training sessions).
  - Customer-focused mindset and a passion for service excellence.
  - Ability to work independently and manage multiple priorities.
  - Manage and coordinate IT Changes, including the classification, assessment, approval, and reviews
  - Chair the Change Advisory Board (CAB), ensuring all changes evaluated for risk, impact, and readiness
  - Maintain Change calendar while monitoring and reporting on Change metrics
  - Oversee communication to impacted users and ensure all changes are properly documented
  - Define and maintain process documentation and ensure compliance and adherence to SLAs (e.g., running CABs or training sessions)
  - Customer-focused mindset and a passion for service excellence.
  - Ability to work independently and manage multiple priorities.