name: Process vacantes and generate YAML files

on:
  push:
    paths:
      - 'vacantes.txt'
      - 'vacantes_sample.txt'

jobs:
  process_vacantes:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Need write permission to commit and push generated files
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install pyyaml

      - name: Process vacantes and generate YAML files
        run: |
          # Function to detect if file is YAML-formatted or plain text
          is_yaml_format() {
            # Check if file contains YAML separators (---) and YAML field markers
            if grep -q "^---$" "$1" && grep -q "^cargo:" "$1" && grep -q "^empresa:" "$1"; then
              return 0  # Is YAML format
            else
              return 1  # Is plain text
            fi
          }
          
          # Process vacantes.txt if it exists and has content
          if [ -f "vacantes.txt" ] && [ -s "vacantes.txt" ]; then
            echo "Processing vacantes.txt..."
            
            if is_yaml_format "vacantes.txt"; then
              echo "Detected YAML format, using process_vacantes.py"
              # Generate YAMLs in vacantes_yaml/ (original copy)
              python scripts/process_vacantes.py --input vacantes.txt --output vacantes_yaml --quiet || true
              # Generate YAMLs in vacantes_yaml_manual/ (editable copy)
              python scripts/process_vacantes.py --input vacantes.txt --output vacantes_yaml_manual --quiet || true
            else
              echo "Detected plain text format, using extract_vacantes_from_text.py"
              # Generate YAMLs in vacantes_yaml/ (original copy)
              python scripts/extract_vacantes_from_text.py --input vacantes.txt --output vacantes_yaml --quiet || true
              # Generate YAMLs in vacantes_yaml_manual/ (editable copy)
              python scripts/extract_vacantes_from_text.py --input vacantes.txt --output vacantes_yaml_manual --quiet || true
            fi
          fi
          
          # Process vacantes_sample.txt if it exists and has content
          if [ -f "vacantes_sample.txt" ] && [ -s "vacantes_sample.txt" ]; then
            echo "Processing vacantes_sample.txt..."
            
            if is_yaml_format "vacantes_sample.txt"; then
              echo "Detected YAML format, using process_vacantes.py"
              # Generate YAMLs in vacantes_yaml/ (original copy)
              python scripts/process_vacantes.py --input vacantes_sample.txt --output vacantes_yaml --quiet || true
              # Generate YAMLs in vacantes_yaml_manual/ (editable copy)
              python scripts/process_vacantes.py --input vacantes_sample.txt --output vacantes_yaml_manual --quiet || true
            else
              echo "Detected plain text format, using extract_vacantes_from_text.py"
              # Generate YAMLs in vacantes_yaml/ (original copy)
              python scripts/extract_vacantes_from_text.py --input vacantes_sample.txt --output vacantes_yaml --quiet || true
              # Generate YAMLs in vacantes_yaml_manual/ (editable copy)
              python scripts/extract_vacantes_from_text.py --input vacantes_sample.txt --output vacantes_yaml_manual --quiet || true
            fi
          fi

      - name: Check for changes
        id: git-check
        run: |
          git diff --exit-code vacantes_yaml/ vacantes_yaml_manual/ || echo "changes=true" >> $GITHUB_OUTPUT

      - name: Commit and push generated YAML files
        if: steps.git-check.outputs.changes == 'true'
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add vacantes_yaml/*.yaml vacantes_yaml_manual/*.yaml
          git commit -m "Auto-generated YAML files from vacantes.txt (original + editable copies)"
          git push
