name: Process vacantes and generate YAML files

on:
  push:
    paths:
      - 'vacantes.txt'
      - 'vacantes_sample.txt'

jobs:
  process_vacantes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install pyyaml

      - name: Process vacantes and generate YAML files
        run: |
          # Process vacantes.txt if it exists and has content
          if [ -f "vacantes.txt" ] && [ -s "vacantes.txt" ]; then
            python scripts/process_vacantes.py --input vacantes.txt --output vacantes_yaml_manual --quiet || true
          fi
          # Process vacantes_sample.txt if it exists and has content
          if [ -f "vacantes_sample.txt" ] && [ -s "vacantes_sample.txt" ]; then
            python scripts/process_vacantes.py --input vacantes_sample.txt --output vacantes_yaml_manual --quiet || true
          fi

      - name: Check for changes
        id: git-check
        run: |
          git diff --exit-code vacantes_yaml_manual/ || echo "changes=true" >> $GITHUB_OUTPUT

      - name: Commit and push generated YAML files
        if: steps.git-check.outputs.changes == 'true'
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add vacantes_yaml_manual/*.yaml
          git commit -m "Auto-generated YAML files from vacantes.txt"
          git push
